import { save } from '@tauri-apps/plugin-dialog';
import { invoke } from '@tauri-apps/api/core';

export interface ExportOptions {
  format: 'pdf' | 'docx' | 'html' | 'pptx' | 'latex' | 'md' | 'epub';
  template?: string;
  quality?: 'low' | 'medium' | 'high';
  includeFrontmatter?: boolean;
  compressImages?: boolean;
  embedFonts?: boolean;
}

export class ExportEnhanced {
  /** 导出 PPTX 幻灯片 */
  static async exportPPTX(markdown: string, title: string = 'Presentation'): Promise<string | null> {
    const path = await save({ filters: [{ name: 'PowerPoint', extensions: ['pptx'] }], defaultPath: `${title}.pptx` });
    if (!path) return null;

    // Split by headings as slides
    const slides = markdown.split(/^#{1,2}\s/gm).filter(Boolean);
    const slideContents = slides.map(s => s.trim());

    // Use pptxgenjs to create file (client-side since it's pure JS)
    try {
      const PPTX = await import('pptxgenjs');
      const pptx = new PPTX.default();
      pptx.layout = 'LAYOUT_WIDE';
      pptx.author = 'Markhere';

      for (const content of slideContents) {
        const slide = pptx.addSlide();
        const lines = content.split('\n').filter(l => l.trim());
        if (lines.length > 0) {
          // First line as title
          slide.addText(lines[0], { x: 0.5, y: 0.5, w: '90%', h: 1, fontSize: 28, bold: true, color: '1a1a1a' });
          if (lines.length > 1) {
            slide.addText(lines.slice(1).join('\n'), { x: 0.5, y: 1.8, w: '90%', h: 4, fontSize: 14, color: '333333' });
          }
        }
      }

      const { writeFile } = await import('@tauri-apps/plugin-fs');
      const data = await pptx.write({ outputType: 'arraybuffer' });
      await writeFile(path, new Uint8Array(data as ArrayBuffer));
      return path;
    } catch (e) {
      // Fallback: save as HTML slides
      const html = generateSlideHTML(markdown, title);
      await invoke('save_file', { path: path.replace(/\.pptx$/, '.html'), content: html });
      return path;
    }
  }

  /** 导出 LaTeX */
  static async exportLaTeX(markdown: string, title: string = 'Document'): Promise<string | null> {
    const path = await save({ filters: [{ name: 'LaTeX', extensions: ['tex'] }], defaultPath: `${title}.tex` });
    if (!path) return null;

    const latex = convertToLaTeX(markdown, title);
    await invoke('save_file', { path, content: latex });
    return path;
  }

  /** 批量导出 */
  static async batchExport(files: { path: string; content: string }[], options: ExportOptions): Promise<string[]> {
    const results: string[] = [];
    for (const f of files) {
      let result: string | null = null;
      switch (options.format) {
        case 'pptx': result = await this.exportPPTX(f.content, f.path.split('/').pop()?.replace('.md', '') || 'slide'); break;
        case 'latex': result = await this.exportLaTeX(f.content, f.path.split('/').pop()?.replace('.md', '') || 'doc'); break;
      }
      if (result) results.push(result);
    }
    return results;
  }
}

/** --- HTML slide generator (fallback) --- */
function generateSlideHTML(md: string, title: string): string {
  const slides = md.split(/^#{1,2}\s/gm).filter(Boolean).map(s => s.trim());
  const slideDivs = slides.map(content => {
    const lines = content.split('\n');
    const h = lines[0]?.replace(/^#+\s*/, '') || '';
    const body = lines.slice(1).join('\n');
    return `<section><h1>${escapeHTML(h)}</h1><div class="content">${body.replace(/\n/g, '<br>')}</div></section>`;
  }).join('\n');

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${escapeHTML(title)}</title>
<style>body{font-family:system-ui,sans-serif;margin:0;background:#1a1a2e;color:#eee;overflow:hidden}
section{display:flex;flex-direction:column;justify-content:center;align-items:center;height:100vh;padding:40px;box-sizing:border-box;page-break-after:always}
h1{font-size:3em;margin-bottom:20px;text-align:center}.content{font-size:1.2em;max-width:800px;text-align:left}</style></head><body>${slideDivs}</body></html>`;
}

/** --- LaTeX converter --- */
function convertToLaTeX(md: string, title: string): string {
  let latex = `\\documentclass[12pt,a4paper]{article}
\\usepackage[utf8]{inputenc}
\\usepackage{geometry}
\\geometry{margin=2.5cm}
\\usepackage{hyperref}
\\usepackage{graphicx}
\\usepackage{listings}
\\usepackage{xcolor}

\\title{${escapeLatex(title)}}
\\author{Generated by Markhere}
\\date{\\today}

\\begin{document}
\\maketitle
\\tableofcontents
\\newpage
`;

  let inCodeBlock = false;
  for (const line of md.split('\n')) {
    if (line.startsWith('```')) { inCodeBlock = !inCodeBlock; latex += inCodeBlock ? '\\begin{lstlisting}\n' : '\\end{lstlisting}\n'; continue; }
    if (inCodeBlock) { latex += line + '\n'; continue; }
    if (line.startsWith('# ')) latex += `\\section{${escapeLatex(line.slice(2))}}\n`;
    else if (line.startsWith('## ')) latex += `\\subsection{${escapeLatex(line.slice(3))}}\n`;
    else if (line.startsWith('### ')) latex += `\\subsubsection{${escapeLatex(line.slice(4))}}\n`;
    else if (line.startsWith('- ')) latex += `\\begin{itemize}\n\\item ${escapeLatex(line.slice(2))}\n\\end{itemize}\n`;
    else if (line.startsWith('> ')) latex += `\\begin{quote}${escapeLatex(line.slice(2))}\\end{quote}\n`;
    else if (line.trim() === '') latex += '\n';
    else latex += `${escapeLatex(line)}\n\n`;
  }
  if (inCodeBlock) latex += '\\end{lstlisting}\n';
  latex += '\\end{document}\n';
  return latex;
}

function escapeHTML(s: string): string { return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }

function escapeLatex(s: string): string {
  return s.replace(/\\/g, '\\textbackslash{}').replace(/[&%$#_{}~^]/g, '\\$&');
}
