export const themes = {
  newsprint: {
    name: 'Newsprint',
    colors: {
      bg: '#F5F5F5',
      text: '#333333',
      border: '#CCCCCC',
      primary: '#2C2C2C',
      codeBg: '#E8E8E8',
      hoverBg: '#EBEBEB',
    },
  },
  github: {
    name: 'Github',
    colors: {
      bg: '#FFFFFF',
      text: '#24292E',
      border: '#E1E4E8',
      primary: '#0366D6',
      codeBg: '#F6F8FA',
      hoverBg: '#F3F4F6',
    },
  },
  medium: {
    name: 'Medium',
    colors: {
      bg: '#FFFFFF',
      text: '#292929',
      border: '#E5E5E5',
      primary: '#00A0DC',
      codeBg: '#F3F3F3',
      hoverBg: '#F9F9F9',
    },
  },
  night: {
    name: 'Night',
    colors: {
      bg: '#1E1E1E',
      text: '#D4D4D4',
      border: '#3E3E3E',
      primary: '#569CD6',
      codeBg: '#2D2D2D',
      hoverBg: '#252526',
    },
  },
  pixie: {
    name: 'Pixie',
    colors: {
      bg: '#FAFAFA',
      text: '#4A4A4A',
      border: '#E0E0E0',
      primary: '#E91E63',
      codeBg: '#F5F5F5',
      hoverBg: '#ECECEC',
    },
  },
  navy: {
    name: 'Navy',
    colors: {
      bg: '#001F3F',
      text: '#FFFFFF',
      border: '#003366',
      primary: '#7FDBFF',
      codeBg: '#00264D',
      hoverBg: '#002B55',
    },
  },
  aqua: {
    name: 'Aqua',
    colors: {
      bg: '#7FDBFF',
      text: '#001F3F',
      border: '#39CCCC',
      primary: '#001F3F',
      codeBg: '#B2EBF2',
      hoverBg: '#B3E5FC',
    },
  },
  classic: {
    name: 'Classic',
    colors: {
      bg: '#FDF6E3',
      text: '#657B83',
      border: '#EEE8D5',
      primary: '#B58900',
      codeBg: '#EEE8D5',
      hoverBg: '#E4DDC8',
    },
  },
  coffee: {
    name: 'Coffee',
    colors: {
      bg: '#3E2723',
      text: '#D7CCC8',
      border: '#5D4037',
      primary: '#BCAAA4',
      codeBg: '#4E342E',
      hoverBg: '#452B23',
    },
  },
  forest: {
    name: 'Forest',
    colors: {
      bg: '#2E7D32',
      text: '#C8E6C9',
      border: '#388E3C',
      primary: '#81C784',
      codeBg: '#1B5E20',
      hoverBg: '#247D28',
    },
  },
  ocean: {
    name: 'Ocean',
    colors: {
      bg: '#004D40',
      text: '#B2DFDB',
      border: '#00695C',
      primary: '#4DB6AC',
      codeBg: '#002F2F',
      hoverBg: '#003D33',
    },
  },
  raspberry: {
    name: 'Raspberry',
    colors: {
      bg: '#880E4F',
      text: '#F8BBD0',
      border: '#AD1457',
      primary: '#F48FB1',
      codeBg: '#6A1B4D',
      hoverBg: '#7B1B55',
    },
  },
  turquoise: {
    name: 'Turquoise',
    colors: {
      bg: '#00ACC1',
      text: '#E0F7FA',
      border: '#0097A7',
      primary: '#26C6DA',
      codeBg: '#00838F',
      hoverBg: '#0091A0',
    },
  },
  solarizedLight: {
    name: 'Solarized Light',
    colors: {
      bg: '#FDF6E3',
      text: '#657B83',
      border: '#EEE8D5',
      primary: '#B58900',
      codeBg: '#EEE8D5',
      hoverBg: '#E4DDC8',
    },
  },
  solarizedDark: {
    name: 'Solarized Dark',
    colors: {
      bg: '#002B36',
      text: '#839496',
      border: '#073642',
      primary: '#268BD2',
      codeBg: '#073642',
      hoverBg: '#042A35',
    },
  },
  oneDark: {
    name: 'One Dark',
    colors: {
      bg: '#282C34',
      text: '#ABB2BF',
      border: '#3E4451',
      primary: '#61AFEF',
      codeBg: '#21252B',
      hoverBg: '#2C313A',
    },
  },
  oneLight: {
    name: 'One Light',
    colors: {
      bg: '#FAFAFA',
      text: '#383A42',
      border: '#E5E5E6',
      primary: '#4078F2',
      codeBg: '#F0F0F0',
      hoverBg: '#ECECEC',
    },
  },
  dracula: {
    name: 'Dracula',
    colors: {
      bg: '#282A36',
      text: '#F8F8F2',
      border: '#44475A',
      primary: '#BD93F9',
      codeBg: '#1E1F29',
      hoverBg: '#3B3C4B',
    },
  },
  monokai: {
    name: 'Monokai',
    colors: {
      bg: '#272822',
      text: '#F8F8F2',
      border: '#3E3D32',
      primary: '#A6E22E',
      codeBg: '#1E1F1C',
      hoverBg: '#232420',
    },
  },
  nord: {
    name: 'Nord',
    colors: {
      bg: '#2E3440',
      text: '#D8DEE9',
      border: '#3B4252',
      primary: '#88C0D0',
      codeBg: '#242933',
      hoverBg: '#343A46',
    },
  },
  gruvboxLight: {
    name: 'Gruvbox Light',
    colors: {
      bg: '#FBF1C7',
      text: '#3C3836',
      border: '#EBDBB2',
      primary: '#D5C4A1',
      codeBg: '#F2E5BC',
      hoverBg: '#EBDBB2',
    },
  },
  gruvboxDark: {
    name: 'Gruvbox Dark',
    colors: {
      bg: '#282828',
      text: '#EBDBB2',
      border: '#3C3836',
      primary: '#D79921',
      codeBg: '#1D2021',
      hoverBg: '#232423',
    },
  },
  materialLighter: {
    name: 'Material Lighter',
    colors: {
      bg: '#FAFAFA',
      text: '#90A4AE',
      border: '#E7E7E7',
      primary: '#39ADB5',
      codeBg: '#E7E7E7',
      hoverBg: '#ECECEC',
    },
  },
  materialDarker: {
    name: 'Material Darker',
    colors: {
      bg: '#212121',
      text: '#EEFFFF',
      border: '#424242',
      primary: '#82AAFF',
      codeBg: '#171717',
      hoverBg: '#1E1E1E',
    },
  },
  materialPalenight: {
    name: 'Material Palenight',
    colors: {
      bg: '#292D3E',
      text: '#A6ACCD',
      border: '#444267',
      primary: '#C792EA',
      codeBg: '#1E2130',
      hoverBg: '#232537',
    },
  },
  materialOceanic: {
    name: 'Material Oceanic',
    colors: {
      bg: '#0F111A',
      text: '#8F93A2',
      border: '#232636',
      primary: '#89DDFF',
      codeBg: '#0A0C12',
      hoverBg: '#12141E',
    },
  },
  ayuLight: {
    name: 'Ayu Light',
    colors: {
      bg: '#FAFAFA',
      text: '#5C6166',
      border: '#E7E7E7',
      primary: '#FFAA33',
      codeBg: '#F0F0F0',
      hoverBg: '#ECECEC',
    },
  },
  ayuMirage: {
    name: 'Ayu Mirage',
    colors: {
      bg: '#1F2430',
      text: '#CCC9C2',
      border: '#393E4D',
      primary: '#F29718',
      codeBg: '#151820',
      hoverBg: '#192029',
    },
  },
  ayuDark: {
    name: 'Ayu Dark',
    colors: {
      bg: '#0A0E14',
      text: '#B3B1AD',
      border: '#1F2430',
      primary: '#F29E74',
      codeBg: '#05070A',
      hoverBg: '#0D1017',
    },
  },
  gotham: {
    name: 'Gotham',
    colors: {
      bg: '#0C1014',
      text: '#599CAD',
      border: '#091F2E',
      primary: '#D3EBE9',
      codeBg: '#080B0E',
      hoverBg: '#0A0F13',
    },
  },
  paperWhite: {
    name: 'Paper White',
    colors: {
      bg: '#FFFFFF',
      text: '#333333',
      border: '#DDDDDD',
      primary: '#333333',
      codeBg: '#F5F5F5',
      hoverBg: '#EEEEEE',
    },
  },
};

export type ThemeName = keyof typeof themes;
export type Theme = typeof themes[ThemeName];